name: update

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
  schedule:
   - cron: '0 0 * * 1'
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: denoland/setup-deno@v1
      - run: |
          sudo apt update
          sudo apt install wget unzip python3 -y

          wget https://github.com/quickjs-ng/quickjs/releases/latest/download/qjs-linux-x86
          chmod 777 ./qjs-linux-x86
          sudo cp ./qjs-linux-x86 /usr/local/bin/qjs-ng

          git clone https://github.com/bellard/quickjs --depth=1
          cd quickjs
          sudo make install
          cd ..

          git clone https://github.com/quickjs-ng/quickjs.git qjs-ng --depth=1
          cd qjs-ng
          sudo make
          sudo cp ./build/qjs /usr/local/bin/qjs-ng
          cd ..

          git clone https://github.com/ccxvii/mujs.git --depth=1
          cd mujs
          sudo make install HAVE_READLINE=no
          cd ..

          git clone https://github.com/saghul/txiki.js --depth=1 --shallow-submodules
          cd txiki.js
          sudo apt install libcurl4-openssl-dev build-essential cmake autoconf texinfo libtool -y
          git submodule update --init
          cmake -S . -B build
          sudo make install
          sudo cp ./build/tjs /usr/local/bin/tjs
          cd ..


          wget https://github.com/boa-dev/boa/releases/latest/download/boa-linux-amd64
          sudo chmod 777 ./boa-linux-amd64
          sudo cp ./boa-linux-amd64 /usr/local/bin/boa


          wget https://github.com/awslabs/llrt/releases/latest/download/llrt-linux-x64.zip
          unzip ./llrt-linux-x64.zip
          sudo cp ./llrt /usr/local/bin/llrt

          git clone https://github.com/jerryscript-project/jerryscript.git --depth=1
          cd jerryscript
          python3 tools/build.py
          sudo cp ./build/bin/jerry /usr/local/bin/jerry

          wget https://github.com/facebook/hermes/releases/latest/download/hermes-cli-linux.tar.gz
          sudo tar -zxvf hermes-cli-linux.tar.gz -C /usr/local/bin

          wget https://github.com/Moddable-OpenSource/moddable/releases/latest/download/xst-lin64.zip
          unzip xst-lin64.zip
          sudo cp ./xst /usr/local/bin/xst


      - name: update
        run: |
          which node
          which deno
          which mujs
          which llrt
          which tjs
          which qjs
          which qjs-ng
          which boa
          which jerry
          which hermes
          which xst

          node --version
          deno --version
          llrt --version
          tjs --version
          boa --version
          jerry --version
          hermes --version
          xst -v


          npm run build
          npm run update > table.txt

          git config --global user.email "504595380@qq.com"
          git config --global user.name "ahaoboy"
          git add ./bench.json ./readme.md ./table.txt
          git commit -m"update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: ./bench.json
