name: update

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 1"
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  bench:
      strategy:
        matrix:
          include:
            - target: macos-amd64
              os: macos-13
            - target: macos-arm64
              os: macos-14
            - target: windows
              os: windows-latest
            - target: ubuntu
              os: ubuntu-24.04
      runs-on: ${{ matrix.os }}
      name: bench-${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - name: install easy-install
          uses: ahaoboy/easy-setup@v1
          with:
            url: https://github.com/ahaoboy/easy-install
        - name: install
          run: |
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/quickjs-ng.json
            mv ~/.easy-install/qjs ~/.easy-install/qjs-ng
            mv ~/.easy-install/qjsc ~/.easy-install/qjsc-ng

            ei https://github.com/denoland/deno
            ei https://github.com/ahaoboy/spidermonkey-build
            ei https://github.com/ahaoboy/v8-build
            ei https://github.com/ahaoboy/jsc-build
            ei https://github.com/ahaoboy/jerryscript-build
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/node.json
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/bun.json
            ei https://github.com/ahaoboy/quickjs-build
            ei https://github.com/ahaoboy/mujs-build
            ei https://github.com/ahaoboy/txiki.js-build
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/boa.json
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/llrt.json
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/hermes.json
            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/xst.json

            ei https://github.com/ahaoboy/easy-install/raw/refs/heads/main/dist-manifest/graaljs.json
            mv ~/.easy-install/graaljs/bin/js ~/.easy-install/graaljs/bin/graaljs

        - name: run
          run: |
            node ./scripts/build.js
            node ./scripts/update.js > ${{ matrix.target }}.json
        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.target }}
            path: ./${{ matrix.target }}.json
  update:
    needs: ["bench"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - uses: actions/download-artifact@v4
        with:
          path: windows
          pattern: windows
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: ubuntu
          pattern: ubuntu
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: macos-amd64
          pattern: macos-amd64
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: macos-arm64
          pattern: macos-arm64
          merge-multiple: true
      - run: |
          cp ./ubuntu/ubuntu.json ./ubuntu.json
          cp ./windows/windows.json ./windows.json
          cp ./macos-amd64/macos-amd64.json ./macos-amd64.json
          cp ./macos-arm64/macos-arm64.json ./macos-arm64.json
          node ./scripts/update-readme.js
          git config --global user.email "504595380@qq.com"
          git config --global user.name "ahaoboy"
          git add ./windows.json ./ubuntu.json ./macos-amd64.json ./macos-arm64.json ./readme.md
          git commit -m"update"
          cat readme.md
      - name: Upload readme
        uses: actions/upload-artifact@v4
        with:
          name: readme
          path: readme.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
